### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Andersson007** [ansible-community/community-examples#2]
TODO:
- [x] Create the repo
- [x] Get real examples
- [x] Implement the dir structure (like in the [comment](https://github.com/ansible-community/community-topics/issues/39#issuecomment-978955575))
- [x] Set up CI
- [x] Integrate the examples in CI
- [ ] Think of possible ways of how to run tests only for a file changed
- [ ] Get feedback from folks (doc, community, steering committee, etc.)
- [ ] Re-evaluate, re-arrange things
- [ ] Complete README with a description, workflow for contributors, etc.
- [ ] Announce

**Comment by samccann** [comment]
@jillr at one point in the dim dawn of time you mentioned there may be some AWS examples 'somewhere' we could pull into this new examples repo... does that sound familiar or am I delusional (or.. well, more delusional than normal )...

**Comment by jillr** [comment]
@samccann If I recall correctly it was [this](https://github.com/ansible-collections/amazon.aws/pull/361), where we swapped out use of the c.g.json_query filter for native Jinja filtering.  We did it to reduce a collection dependency in CI, but it could also be used to show 2 different approaches to accessing complex data.  I'll try to think if there are any others.

ETA: Oh I already thought of another one!  These tests have a bunch of items2dict examples  https://github.com/ansible-collections/amazon.aws/blob/main/tests/integration/targets/ec2_vpc_dhcp_option/tasks/main.yml

**Comment by samccann** [comment]
Thanks @jillr i converted both to issues here so we don't lose track.

**Comment by acozine** [comment]
The examples in the module documentation are easy to read and can be copy/pasted. How closely can we reproduce that ease of use in this repo? These examples are likely to be used by beginners, after all. Can we either reproduce the actual examples (not just symlinks) in the `examples/` directories, or provide a detailed description of the pattern, and how to read and understand the tests?

**Comment by Andersson007** [comment]
There are no signs of activity here.
Maybe ansible-core module/plugin's docs or collections docs is a more appropriate place for examples.
I'm not sure if we should continue to ask the community for more examples and/or to go further to advertise it across the community (i.e. invest more time and effort).
I believe if there were a strong need, people would naturally talk about it and gather around the repo.
I suggest archiving the repo, thoughts?
[If not objections, I'll do it next week]

**Comment by acozine** [comment]
+1 for archiving this repo. It hasn't been an inviting user experience for either contributors or users. If there's still a need for examples for templating and filtering, let's find a different approach.

**Comment by samccann** [comment]
Something else to keep in mind - when this repo was created, we didn't have any ansible filter examples. We now have them included. See https://docs.ansible.com/ansible/devel/collections/ansible/builtin/items2dict_filter.html for example.

**Comment by samccann** [comment]
+1 for archiving
